# Generated by Django 3.2.7 on 2021-10-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=250)),
                ('station', models.CharField(max_length=250)),
                ('code', models.IntegerField()),
                ('prefix', models.CharField(max_length=3)),
            ],
        ),
    ]
