# Generated by Django 3.2.7 on 2021-10-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railways_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways_api.city'),
        ),
    ]
