# Generated by Django 3.2.7 on 2021-10-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railways_api', '0002_auto_20211010_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='prefix',
        ),
    ]
