# Generated by Django 3.2.7 on 2021-10-21 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('railways_api', '0003_remove_station_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('from_city', models.CharField(max_length=150)),
                ('to_city', models.CharField(max_length=150)),
                ('credit', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.IntegerField()),
                ('price_ticket', models.FloatField(blank=True)),
                ('flight_number', models.CharField(blank=True, max_length=10)),
                ('train_number', models.CharField(blank=True, max_length=10)),
                ('date_departure', models.DateField()),
                ('date_arrival', models.DateField()),
                ('station_from', models.CharField(max_length=250)),
                ('station_to', models.CharField(max_length=250)),
                ('business_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.businesstrip')),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_from', to='railways_api.city')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_to', to='railways_api.city')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.CharField(max_length=150)),
                ('adress', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('business_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.businesstrip')),
            ],
        ),
    ]
