# Generated by Django 3.2.7 on 2021-10-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='train_number',
        ),
        migrations.AddField(
            model_name='trip',
            name='is_first',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='transport_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
