# Generated by Django 3.2.7 on 2021-11-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_usertelegram_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='telephone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
