# Generated by Django 3.2.9 on 2021-11-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_hotel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='link',
            field=models.URLField(max_length=1000),
        ),
    ]
