# Generated by Django 3.2.9 on 2021-12-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_hotel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='id_telegram',
            field=models.IntegerField(max_length=9),
        ),
    ]
