# Generated by Django 3.2.9 on 2021-12-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_alter_usertelegram_id_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstrip',
            name='status',
        ),
    ]
