# Generated by Django 3.2.9 on 2021-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_remove_businesstrip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='id_telegram',
            field=models.IntegerField(),
        ),
    ]
