# Generated by Django 2.2.24 on 2021-11-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviasales_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airport',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
