# Generated by Django 2.2.24 on 2021-10-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviasales_api', '0003_auto_20211030_2148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
