# Generated by Django 2.2.24 on 2021-10-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviasales_api', '0004_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=250)),
            ],
        ),
    ]
