# Generated by Django 2.2.24 on 2021-10-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviasales_api', '0005_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
