# Generated by Django 2.2.24 on 2021-10-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aviasales_api', '0008_auto_20211031_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('airport', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=250)),
            ],
        ),
    ]
